using System.ComponentModel;

namespace TimeVersion
{
    public enum EPaises
    {
        [Description("Brasil")] BR,
        [Description("Estados Unidos")] US,
        [Description("Canadá")] CA,
        [Description("Reino Unido")] UK,
        [Description("França")] FR,
        [Description("Alemanha")] DE,
        [Description("Japão")] JP,
        [Description("China")] CN,
        [Description("Índia")] IN,
        [Description("Austrália")] AU,
        [Description("Itália")] IT,
        [Description("Rússia")] RU,
        [Description("Coreia do Sul")] KR,
        [Description("México")] MX,
        [Description("Espanha")] ES,
        [Description("Argentina")] AR,
        [Description("Indonésia")] ID,
        [Description("África do Sul")] ZA,
        [Description("Nigéria")] NG,
        [Description("Arábia Saudita")] SA,
        [Description("Nova Zelândia")] NZ,
        [Description("Suíça")] CH,
        [Description("Portugal")] PT,
        [Description("Turquia")] TR,
        [Description("Suécia")] SE,
        [Description("Polônia")] PL,
        [Description("Holanda")] NL,
        [Description("Bélgica")] BE,
        [Description("Singapura")] SG,
        [Description("Malásia")] MY,
        [Description("Tailândia")] TH,
        [Description("Vietnã")] VN,
        [Description("Filipinas")] PH,
        [Description("Dinamarca")] DK,
        [Description("Finlândia")] FI,
        [Description("Noruega")] NO,
        [Description("Áustria")] AT,
        [Description("Chile")] CL,
        [Description("Colômbia")] CO,
        [Description("Peru")] PE,
        [Description("Equador")] EC,
        [Description("Venezuela")] VE,
        [Description("Uruguai")] UY,
        [Description("Paraguai")] PY,
        [Description("Bolívia")] BO,
        [Description("Costa Rica")] CR,
        [Description("Panamá")] PA,
        [Description("Cuba")] CU,
        [Description("República Dominicana")] DO,
        [Description("Guatemala")] GT,
        [Description("Honduras")] HN,
        [Description("Nicarágua")] NI,
        [Description("El Salvador")] SV,
        [Description("Haiti")] HT,
        [Description("Jamaica")] JM,
        [Description("Bahamas")] BS, 
        [Description("Barbados")] BB,
        [Description("Trinidad e Tobago")] TT,
        [Description("Angola")] AO,
        [Description("Israel")] IL,
    }
}
