
name: Teste Deploy

on:
  push:
    branches: [ "master" ]

env:
  CAMINHO: TimeVersion\TimeVersion.csproj

jobs:
  deploy:
      runs-on: windows-latest
      steps:
      - name: Checagem
        uses: actions/checkout@v2

      - name: Instalacao .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restauracao de Dependencias
        run: dotnet restore ${{ env.CAMINHO }} 
  
      - name: Compilacao dos Arquivos
        run: dotnet build ${{ env.CAMINHO }} -c Release --no-restore
      
      - name: Publicacao do Software
        run: dotnet publish ${{ env.CAMINHO }} -c Release --self-contained -r win-x64 -p:PublishSingleFile=True --no-build
  
      - uses: action/create-release@v1
        id: create_release
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      # - uses: Weather_WPF/release-asset-actions@v2
      #   with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    pattern: Downloads\apps\app.publish\*.exe   
      #    release-url: ${{ steps.create_release.outputs.upload_url }}
